
# This line specifies the version of the Docker Compose file format. In this case, it is version 3, which is the latest version as of writing.
version: '3.11'


# This line starts the definition of the services that make up the application. In this case, there is only one service defined, which is the web service.
services:
  # This line starts the definition of the web service.
  web:
    # This line specifies the location of the Dockerfile for building the web service. In this case, it is the current directory (.).
    build: .
 
    command: uvicorn main:app --host 0.0.0.0 --port 10000

    volumes:
      - .:/code
    # This line maps a port from the host machine to the web service container. In this case, it maps port 8000 on the host to port 8000 in the container. This allows the application running in the container to be accessible from the host machine on port 8000.
    ports:
      - "10000:10000"
